last

diff --git a/.github/workflows/dev-cicd-aws.yaml b/.github/workflows/dev-cicd-aws.yaml
--- a/.github/workflows/dev-cicd-aws.yaml
+++ b/.github/workflows/dev-cicd-aws.yaml
@@ -15,82 +15,82 @@ jobs:
   verify_pipeline:
     environment: runner
     runs-on: ubuntu-latest
-    # services:
-    #   mysql:
-    #     image: mysql:8.0
-    #     env:
-    #       # root 계정 비밀번호
-    #       MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
-    #       # 사용자 계정
-    #       MYSQL_USER: ${{ secrets.MYSQL_USER }}
-    #       # 사용자 계정 비밀번호
-    #       MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
-    #       # 사용자 계정 데이터베이스
-    #       MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
-    #     ports:
-    #       - 3306:3306
-    #     options: >-
-    #       --health-cmd="mysqladmin ping"
-    #       --health-interval=10s
-    #       --health-timeout=5s
-    #       --health-retries=3
+    services:
+      mysql:
+        image: mysql:8.0
+        env:
+          # root 계정 비밀번호
+          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
+          # 사용자 계정
+          MYSQL_USER: ${{ secrets.MYSQL_USER }}
+          # 사용자 계정 비밀번호
+          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
+          # 사용자 계정 데이터베이스
+          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
+        ports:
+          - 3306:3306
+        options: >-
+          --health-cmd="mysqladmin ping"
+          --health-interval=10s
+          --health-timeout=5s
+          --health-retries=3
 
     steps:
-    # - name: 소스코드 다운로드
-    #   uses: actions/checkout@v4 
+    - name: 소스코드 다운로드
+      uses: actions/checkout@v4 
 
-    # - name: JDK 17 설치
-    #   uses: actions/setup-java@v4
-    #   with:
-    #     java-version: '17'
-    #     distribution: 'temurin'
+    - name: JDK 17 설치
+      uses: actions/setup-java@v4
+      with:
+        java-version: '17'
+        distribution: 'temurin'
         
-    # - name: change application.yml
-    #   run: |
-    #     cat > src/main/resources/application.yml << EOF
-    #     spring:
-    #       datasource:
-    #         url: ${{ secrets.DATABASE_URL }} # 예dbc:mysql://localhost:3306/istory
-    #         username: ${{ secrets.MYSQL_USER }}
-    #         password: ${{ secrets.MYSQL_PASSWORD }}
-    #         driver-class-name: com.mysql.cj.jdbc.Driver
-    #       jpa:
-    #         database-platform: org.hibernate.dialect.MySQL8Dialect
-    #         hibernate:
-    #           ddl-auto: update
-    #         show-sql: true
-    #       application:
-    #         name: USER-SERVICE
-    #       jwt:
-    #         issuer: user@gmail.com
-    #         secret_key: study-springboot
-    #     management:
-    #       endpoints:
-    #         web:
-    #           exposure:
-    #             include: health,info
-    #       endpoint:
-    #         health:
-    #           show-details: always
-    #     EOF
-    # - name: 테스트 수행
-    #   run: ./gradlew test
+    - name: change application.yml
+      run: |
+        cat > src/main/resources/application.yml << EOF
+        spring:
+          datasource:
+            url: ${{ secrets.DATABASE_URL }} # 예dbc:mysql://localhost:3306/istory
+            username: ${{ secrets.MYSQL_USER }}
+            password: ${{ secrets.MYSQL_PASSWORD }}
+            driver-class-name: com.mysql.cj.jdbc.Driver
+          jpa:
+            database-platform: org.hibernate.dialect.MySQL8Dialect
+            hibernate:
+              ddl-auto: update
+            show-sql: true
+          application:
+            name: USER-SERVICE
+          jwt:
+            issuer: user@gmail.com
+            secret_key: study-springboot
+        management:
+          endpoints:
+            web:
+              exposure:
+                include: health,info
+          endpoint:
+            health:
+              show-details: always
+        EOF
+    - name: 테스트 수행
+      run: ./gradlew test
 
-    # - name: 테스트 검사 후 실패 시 파이프라인 중단
-    #   if: failure()
-    #   run: |
-    #     echo "Tests failed! Pipeline will be stopped."
-    #     exit 1
+    - name: 테스트 검사 후 실패 시 파이프라인 중단
+      if: failure()
+      run: |
+        echo "Tests failed! Pipeline will be stopped."
+        exit 1
 
-    # - name: 테스트 결과를 STEP Summary 에 업로드
-    #   if: always()
-    #   uses: actions/upload-artifact@v4
-    #   with:
-    #     name: test-report
-    #     path: |                    # 여러 경로 지정
-    #       **/build/reports/tests/test/
-    #       **/build/test-results/test/
-    #     retention-days: 30 
+    - name: 테스트 결과를 STEP Summary 에 업로드
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: test-report
+        path: |                    # 여러 경로 지정
+          **/build/reports/tests/test/
+          **/build/test-results/test/
+        retention-days: 30 
 
     - name: 기본 수행정보 Step Summary 에 표시
       run: |
@@ -101,65 +101,65 @@ jobs:
         echo "* 실행 저장소: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
         echo "* 실행 브랜치: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
 
-    # - name: 코드 컨벤션 규칙 검사
-    #   run: |
-    #     mkdir -p build/reports/checkstyle
-    #     ./gradlew checkstyleMain checkstyleTest --info
-    #     ls -la build/reports/checkstyle || true 
+    - name: 코드 컨벤션 규칙 검사
+      run: |
+        mkdir -p build/reports/checkstyle
+        ./gradlew checkstyleMain checkstyleTest --info
+        ls -la build/reports/checkstyle || true 
 
-    # - name: 코드 컨벤션 검사 결과 업로드
-    #   if: always()
-    #   uses: actions/upload-artifact@v4
-    #   with:
-    #     name: checkstyle-report
-    #     path: build/reports/checkstyle/
-    #     retention-days: 14
-    # - name: Generate list using Markdown
-    #   run: |
-    #     echo "## 코드 스타일 분석결과" >> $GITHUB_STEP_SUMMARY
-    #     echo "" >> $GITHUB_STEP_SUMMARY
-    #     if [ -f build/reports/checkstyle/main.xml ]; then # 소스분석결과 존재시
-    #       echo "### 소스분석결과" >> $GITHUB_STEP_SUMMARY
-    #       echo '```' >> $GITHUB_STEP_SUMMARY
-    #       cat build/reports/checkstyle/main.xml >> $GITHUB_STEP_SUMMARY
-    #       echo '```' >> $GITHUB_STEP_SUMMARY
-    #     fi
-    # - name: CodeQL 초기화
-    #   uses: github/codeql-action/init@v3
-    #   with:
-    #     languages: java
-    #     queries: security-and-quality
+    - name: 코드 컨벤션 검사 결과 업로드
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: checkstyle-report
+        path: build/reports/checkstyle/
+        retention-days: 14
+    - name: Generate list using Markdown
+      run: |
+        echo "## 코드 스타일 분석결과" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        if [ -f build/reports/checkstyle/main.xml ]; then # 소스분석결과 존재시
+          echo "### 소스분석결과" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          cat build/reports/checkstyle/main.xml >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+        fi
+    - name: CodeQL 초기화
+      uses: github/codeql-action/init@v3
+      with:
+        languages: java
+        queries: security-and-quality
 
-    # - name: 코드 빌드
-    #   uses: github/codeql-action/autobuild@v3
+    - name: 코드 빌드
+      uses: github/codeql-action/autobuild@v3
 
-    # - name: 보안 취약점 분석
-    #   uses: github/codeql-action/analyze@v3
-    #   with:
-    #     category: "/language:java"
-    #     output: sarif-results
+    - name: 보안 취약점 분석
+      uses: github/codeql-action/analyze@v3
+      with:
+        category: "/language:java"
+        output: sarif-results
 
-    # - name: 보안취약점 분석 요약
-    #   run: |
-    #     echo "# 파이프라인 리포트" >> $GITHUB_STEP_SUMMARY
-    #     echo "## 보안 경고" >> $GITHUB_STEP_SUMMARY
+    - name: 보안취약점 분석 요약
+      run: |
+        echo "# 파이프라인 리포트" >> $GITHUB_STEP_SUMMARY
+        echo "## 보안 경고" >> $GITHUB_STEP_SUMMARY
         
-    #     if [ -f sarif-results/java.sarif ]; then
-    #       if jq -e '.runs[0].results' sarif-results/java.sarif > /dev/null 2>&1; then
-    #         ALERTS=$(jq '.runs[].results | length' sarif-results/java.sarif)
-    #         echo "${ALERTS}개의 잠재적인 보안 이슈가 발견 되었습니다." >> $GITHUB_STEP_SUMMARY
+        if [ -f sarif-results/java.sarif ]; then
+          if jq -e '.runs[0].results' sarif-results/java.sarif > /dev/null 2>&1; then
+            ALERTS=$(jq '.runs[].results | length' sarif-results/java.sarif)
+            echo "${ALERTS}개의 잠재적인 보안 이슈가 발견 되었습니다." >> $GITHUB_STEP_SUMMARY
             
-    #         echo "### 보안 경고 상세" >> $GITHUB_STEP_SUMMARY
-    #         echo "| Severity | Rule | Description | File |" >> $GITHUB_STEP_SUMMARY
-    #         echo "|----------|------|-------------|------|" >> $GITHUB_STEP_SUMMARY
+            echo "### 보안 경고 상세" >> $GITHUB_STEP_SUMMARY
+            echo "| Severity | Rule | Description | File |" >> $GITHUB_STEP_SUMMARY
+            echo "|----------|------|-------------|------|" >> $GITHUB_STEP_SUMMARY
             
-    #         jq -r '.runs[].results[] | "| \(.properties.security_severity // "medium") | \(.ruleId // "N/A") | \(.message.text // "N/A") | \(.locations[0].physicalLocation.artifactLocation.uri):\(.locations[0].physicalLocation.region.startLine) |"' sarif-results/java.sarif >> $GITHUB_STEP_SUMMARY || true
-    #       else
-    #         echo "No results found in SARIF file." >> $GITHUB_STEP_SUMMARY
-    #       fi
-    #     else
-    #       echo "No SARIF results file found." >> $GITHUB_STEP_SUMMARY
-    #     fi
+            jq -r '.runs[].results[] | "| \(.properties.security_severity // "medium") | \(.ruleId // "N/A") | \(.message.text // "N/A") | \(.locations[0].physicalLocation.artifactLocation.uri):\(.locations[0].physicalLocation.region.startLine) |"' sarif-results/java.sarif >> $GITHUB_STEP_SUMMARY || true
+          else
+            echo "No results found in SARIF file." >> $GITHUB_STEP_SUMMARY
+          fi
+        else
+          echo "No SARIF results file found." >> $GITHUB_STEP_SUMMARY
+        fi
   load-test:
     runs-on: ubuntu-latest
     environment: runner
