first

diff --git a/.github/workflows/java-web-cicd.yaml b/.github/workflows/java-web-cicd.yaml
--- a/.github/workflows/java-web-cicd.yaml
+++ b/.github/workflows/java-web-cicd.yaml
@@ -2,26 +2,45 @@ name: Java cicd
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "develop","main" ]
   pull_request:
-    branches: [ "main" ]
+    branches: [ "develop","main" ]
 
 jobs:
+  determine-environment:
+    runs-on: ubuntu-latest
+    outputs:
+      environment: ${{ steps.set-env.outputs.environment }}
+    steps:
+      - name: Set environment
+        id: set-env
+        run: |
+          if [[ ${{ github.ref }} == refs/heads/main ]]; then
+            echo "environment=prd" >> $GITHUB_OUTPUT
+          elif [[ ${{ github.ref }} == refs/heads/develop ]]; then
+            echo "environment=dev" >> $GITHUB_OUTPUT
+          else
+            echo "Error: Branch must be either 'main' or 'develop'"
+            exit 1
+          fi
   build:
     permissions:
       contents: read
       actions: read
       checks: write    # 테스트 결과 보고를 위한 권한3
       security-events: write # CodeQL 보안
+    needs: determine-environment
+    environment: ${{ needs.determine-environment.outputs.environment }}
+
     runs-on: ubuntu-latest
     services:
       mysql:
         image: mysql:8.0
         env:
-          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
+          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
           MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
-          MYSQL_USER: ${{ secrets.MYSQL_USER }}
-          MYSQL_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
+          MYSQL_USER: ${{ secrets.MYSQL_USERNAME }}
+          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
         ports:
           - 3306:3306
         options: >-
@@ -30,7 +49,9 @@ jobs:
           --health-timeout=5s
           --health-retries=3
     steps:
-    - uses: actions/checkout@v4
+    - name: Source Code Checkout
+      uses: actions/checkout@v4 
+
     - name: Set up JDK 17
       uses: actions/setup-java@v4
       with:
