first

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -40,3 +40,45 @@ jobs:
         distribution: 'temurin'
     - name: Run test java
       run: ./gradlew test
+    - name: Generate list using Markdown
+      run: |
+        echo "## 워크플로우 실행 정보 요약" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        echo "* 실행 담당자: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
+        echo "* 실행 이벤트: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
+        echo "* 실행 저장소: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
+        echo "* 실행 브랜치: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
+        echo "## 코드 스타일 분석결과" >> $GITHUB_STEP_SUMMARY
+        echo "" >> $GITHUB_STEP_SUMMARY
+        if [ -f build/reports/checkstyle/main.xml ]; then # 소스분석결과 존재시
+          echo "### 소스분석결과" >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+          cat build/reports/checkstyle/main.xml >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+        fi
+    - name: Upload Test Report
+      if: always()
+      uses: actions/upload-artifact@v4
+      with:
+        name: test-report
+        path: |                    # 여러 경로 지정
+          **/build/reports/tests/test/
+          **/build/test-results/test/
+        retention-days: 30
+    - name: Notify on Failure
+      if: failure()
+      run: |
+        echo "Tests failed! Pipeline will be stopped."
+        exit 1
+    - name: Install k6
+      run: |
+        curl -L https://github.com/grafana/k6/releases/download/v0.49.0/k6-v0.49.0-linux-amd64.tar.gz -o k6.tar.gz
+        tar -xzf k6.tar.gz
+        sudo cp k6-v0.49.0-linux-amd64/k6 /usr/local/bin/
+
+    - name: Run k6 load test
+      run: |
+        k6 run src/test/load/load-test.js
+      env:
+        K6_VIRTUAL_USERS: 10
+        K6_DURATION: "30s"
